export const FETCH_CONTACTS_SUCCESS = "FETCH_CONTACTS_SUCCESS";
export const FETCH_CONTACTS_FAILURE = "FETCH_CONTACTS_FAILURE";

export const ADD_CONTACT_FAILURE = "ADD_CONTACT_FAILURE";

export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE";

export const EDIT_CONTACT_FAILURE = "EDIT_CONTACT_FAILURE";